baseURL = 'https://maximoschro.github.io/'
languageCode = 'en-us'
title = "Max Schroeder | Game Systems Designer"
theme = 'PaperMod'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 1

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "contact/"
    weight = 2


[params]
  imgPath = "img"

[imageProcessing]
  autoResize = false
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'
    